export const PRODUCTS = [
  {
    id: 1,
    name: "Classic White Sneakers",
    category: "Shoes",
    price: 59.99,
    description: "Comfortable and stylish everyday sneakers.",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500",
  },
  {
    id: 2,
    name: "Minimalist Leather Watch",
    category: "Accessories",
    price: 129.99,
    description: "Sleek leather watch with a modern design.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
  },
  {
    id: 3,
    name: "Canvas Backpack",
    category: "Bags",
    price: 85.0,
    description: "Durable backpack perfect for school or travel.",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
  },
  {
    id: 4,
    name: "Canvas Backpack",
    category: "Bags",
    price: 85.0,
    description: "Durable backpack perfect for school or travel.",
    image: "/laptop1.jpg",
  },
  {
    id: 5,
    name: "Canvas Backpack",
    category: "Bags",
    price: 85.0,
    description: "Durable backpack perfect for school or travel.",
    image: "/laptop2.jpg",
  },
  {
    id: 6,
    name: "Canvas Backpack",
    category: "Bags",
    price: 85.0,
    description: "Durable backpack perfect for school or travel.",
    image: "/laptop1.jpg",
  },
  {
    id: 7,
    name: "Canvas Backpack",
    category: "Bags",
    price: 85.0,
    description: "Durable backpack perfect for school or travel.",
    image: "/laptop2.jpg",
  },
];
